import com.ftn.sbnz.model.events.ActivityEvent;

declare ActivityEvent
    extends com.ftn.sbnz.model.events.ActivityEvent
    @role(event)
    @timestamp(startTimestamp)
end

declare KeyStrokeEvent
    extends com.ftn.sbnz.model.events.KeyStrokeEvent
    @role(event)
    @timestamp(ts)
end

declare AppFocusEvent
    extends com.ftn.sbnz.model.events.AppFocusEvent
    @role(event)
    @timestamp(ts)
end

declare UserBreakEvent
    extends com.ftn.sbnz.model.events.UserBreakEvent
    @role(event)
    @timestamp(ts)
end

declare ScreenTimeEvent
    extends com.ftn.sbnz.model.events.ScreenTimeEvent
    @role(event)
    @timestamp(ts)
end

declare FocusDropEvent
    extends com.ftn.sbnz.model.events.FocusDropEvent
    @role(event)
    @timestamp(ts)
end

declare PassiveBingeEvent
    extends com.ftn.sbnz.model.events.PassiveBingeEvent
    @role(event)
    @timestamp(ts)
end

declare NoBreakStreakEvent
    extends com.ftn.sbnz.model.events.NoBreakStreakEvent
    @role(event)
    @timestamp(ts)
end

declare MultiTaskOverloadEvent
    extends com.ftn.sbnz.model.events.MultiTaskOverloadEvent
    @role(event)
    @timestamp(ts)
end

declare EarlyFatigueSignal
    extends com.ftn.sbnz.model.events.EarlyFatigueSignal
    @role(event)
    @timestamp(ts)
end

declare MentalFatigueSignal
    extends com.ftn.sbnz.model.events.MentalFatigueSignal
    @role(event)
    @timestamp(ts)
end

rule "Detect typing drop"
when
    // 60-min baseline
   $baseline: Double() from accumulate(
       $e: KeyStrokeEvent() over window:time(60m),
       average($e.charsPerMin)
   )
   $baselineError: Double() from accumulate(
       $e: KeyStrokeEvent() over window:time(60m),
       average($e.errorRate)
   )

   $windowAvg: Double() from accumulate(
       $e: KeyStrokeEvent() over window:time(15m),
       average($e.charsPerMin)
   )
   $windowError: Double() from accumulate(
       $e: KeyStrokeEvent() over window:time(15m),
       average($e.errorRate)
   )


    eval($windowAvg <= 0.75 * $baseline && $windowError >= 1.4 * $baselineError)
then
    insert(new FocusDropEvent(System.currentTimeMillis()));
end

rule "Detect passive binge"
when
    $lastTs: Long() from accumulate(
        $e: AppFocusEvent(category == "SOCIAL") over window:time(10m),
        init( Long ts = 0L; ),
        action( ts = $e.getTs(); ),
        result( ts )
    )
    $count: Number() from accumulate(
        $e: AppFocusEvent(category == "SOCIAL") over window:time(10m),
        count($e)
    )
    eval($count.intValue() >= 3)
then
    insert(new PassiveBingeEvent($lastTs));
end


rule "Detect no-break streak"
when
    $lastTs: Long() from accumulate(
        $e: ActivityEvent(breakDuration < 5) over window:time(90m),
        init( Long ts = 0L; ),
        action( ts = $e.getStartTimestamp(); ),
        result( ts )
    )
    $sumActive: Number() from accumulate(
        $e: ActivityEvent(breakDuration < 5) over window:time(90m),
        sum($e.activityDuration)
    )
    eval($sumActive.doubleValue() >= 90)
then
    insert(new NoBreakStreakEvent($lastTs));
end



rule "Detect multitask overload"
when
    $lastTs: Long() from accumulate(
        $e: AppFocusEvent() over window:time(2h),
        init( Long ts = 0L; ),
        action( ts = $e.ts; ),
        result( ts )
    )
    $count: Number() from accumulate(
        $e: AppFocusEvent() over window:time(2h),
        count($e)
    )
    eval($count.intValue() >= 30)
then
    insert(new MultiTaskOverloadEvent($lastTs));
end


rule "Early fatigue"
when
    $focus: FocusDropEvent()
    $nobreak: NoBreakStreakEvent()
    eval(Math.abs($nobreak.ts - $focus.ts) <= 30*60*1000)
then
    insert(new EarlyFatigueSignal(Math.max($focus.ts, $nobreak.ts)));
end

rule "Mental fatigue"
when
    $binge: PassiveBingeEvent()
    $nobreak: NoBreakStreakEvent()
    eval(Math.abs($binge.ts - $nobreak.ts) <= 45*60*1000)
then
    insert(new MentalFatigueSignal(Math.max($binge.ts, $nobreak.ts)));
end
